### ISSUE TITLE
Sprint One Bugs

### ISSUE THREAD

**Issue by Nathan-O** [JstnRegi/Wanderful#23]
Bugs that i've found near the end of Spring 1:

-- When logged in, Nav bar still reads "Sign up" and "Login".
-- Can see other user's profiles
-- Can login with incorrect password.
-- Need more link buttons (for cities and post pages, thus far they are unreachable)
-- Cannot see Log (posts) author (on city show page).
-- /cities/new redirects to /city/:id (city show page)
-- Post titles aren't linked to full article (full article is listed on page instead)

**Comment by JustinRegiReyes** [comment]
You squashed the own bugs you found
